name: CD

permissions:
  contents: read
  packages: write

# on:
#   workflow_run:
#     workflows: ["Check pull request"]
#     types:
#       - completed

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /usr/local/bin/docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
            /usr/local/bin/docker stop project1 || true
            /usr/local/bin/docker rm project1 || true
            /usr/local/bin/docker run -d --name project1 -p 8080:80 ghcr.io/${{ github.repository }}:${{ github.sha }}
